### ISSUE TITLE
Matchmaking online players (in lobby) and sending them to a game session

### ISSUE THREAD

**Issue by pixelkingliam** [ExtractIntoVoid/EIV_Lobby#1]
Implement matchmaking for players queued onto a map. Upon having enough players queued for a map they should be sent onto a new game session.

**Comment by SlejmUr** [comment]
Also addition for maps, in your ini you should be able to control how many is the minimum/maximum player. 
Currently don't exceed 32. (Godot limitations?)

This should be inside godot (min/max) instead of here?

**Comment by pixelkingliam** [comment]
since maps would be part of mods, they could be set inside the map definition in the mod, that would be sent over to the client and the server during mod loads, we can give an load error if the max player is > 25

**Comment by SlejmUr** [comment]
Connection from Server to Lobby happens after mod loads, and map started.
Can easily get those and only require to add some settings into BaseWorld in EIV_Game

**Comment by SlejmUr** [comment]
Added MD file for these.
Will work on it following with that file.

**Comment by SlejmUr** [comment]
This is done in Lobby side. Have to implement In-Game.
[Mod sync currently not implement]
